Fixed Memory Leak
richardelms/FileBasedPlayerPrefs pull request #4
Opened 2021-07-15 03:09 UTC by pabloleban

Using a string += string multiple times result in garbage allocation which ended up crashing my game after having it opened for too long. This fixes the issue.
Thanks for this awesome lib!

2021-07-25 10:08 UTC, rahebn approved these changes

2021-07-26 13:09 UTC, rahebn requested changes

2021-07-26 13:09 UTC, rahebn commented on Assets/Plugins/FileBasedPrefs/FileBasedPrefs.cs
> +        return res.ToString();
this should probably be `return sb.ToString();`

2021-11-12 13:37 UTC, richardelms approved these changes
Very cool, thanks!

2021-11-12 13:38 UTC, merged